name: Update gist (producitve-box)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    environment: gist
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 91363826fd43a6a977093adea6c0eb18
          TIMEZONE: Asia/Seoul
